@startuml

'##############################################
' 2020/05/11 吉冨 新規作成
'##############################################

title テストサンプル クラス図

' --------------------------------------------
' Domain
' --------------------------------------------

' Exceptions
package FeederSerial <<Frame>> {

   package Views <<Frame>> {
      'View(Form)
      class AnalyzeView <<View>>{
         - string SearchText
         - string SearcheLabel
         - void Search()
      }
   }

   package ViewsModel <<Frame>> {

      ' ViewModel
      class AnalyzeViewModel <<ViewModel>> {
         + string SearchText
         + string SearcheLabel
         + void Search()
      }

      ' Logic
      class Analyze {
         + int Sum()
         + int Ave()
      }
   }

   package DAO <<Frame>> {

      ' インターフェイス
      interface IDataBase <<Interface>>{
         --
         + int GetDataBaseValue()
      }

      ' SQL
      class DataBaseDAO {
         --
         + int GetDataBaseValue()
      }

   }

   ' Mock
   class Moq <<M,Mock>>{
      --
      + int GetDataBaseValue()
   }
   note bottom
      実際はTestプロジェクトの中
   end note

}

' --------------------------------------------
' Tests
' --------------------------------------------
package Tests.Test <<Frame>>{

   class AnalyzeViewModelTest <<Test>>{
      + シナリオ()
   }


}

' --------------------------------------------
' データベース
' --------------------------------------------
package DB  {
   database Postgres {
   }
}

'----------------------------------------------
'リレーション
'----------------------------------------------
AnalyzeView <-> AnalyzeViewModel

AnalyzeViewModelTest --> AnalyzeViewModel
AnalyzeViewModel <-- Analyze
AnalyzeViewModel <-- IDataBase

IDataBase <.. DataBaseDAO
IDataBase <.. Moq

DataBaseDAO .. Postgres

@enduml